"""Curated AXL definitions: verb -> measurable patterns. Claim text and thresholds are written by AXL; each pattern cites
verbatim source quotes (regex-located in the saved texts at build time, the build fails if one is missing). A pattern is only
`enforced` if its receipts exist (apply_receipts.py). Syntax examples are examples, not the explanation."""
IMP = lambda n: f"https://github.com/pbakaus/impeccable/blob/main/skill/reference/{n}.md"
WCAG = "https://www.w3.org/TR/WCAG22/"
CONTRAST = "https://www.w3.org/WAI/WCAG22/Understanding/contrast-minimum.html"
AXE = "https://github.com/dequelabs/axe-core"
MDN = "https://developer.mozilla.org/en-US/docs/Web/CSS/@media/prefers-reduced-motion"

VERBS = {
 "polish": {"plain": "Finish what is already there. Nothing off the spacing grid, nothing too faint to read, nothing you cannot reach with a keyboard. Polish never redesigns; it only removes defects that a tool can count.",
            "stays_subjective": "Whether the result feels 'refined' overall."},
 "layout": {"plain": "Give content a predictable rhythm and a readable line, and make sure it still fits when the screen is narrow.",
            "stays_subjective": "Whether the composition is 'balanced' or 'has breathing room'."},
 "typeset": {"plain": "Make text comfortable to read: big enough, spaced enough, and not too wide.",
             "stays_subjective": "Whether the typeface has the right personality."},
 "adapt": {"plain": "Make the same interface work on a phone and on a desktop: targets you can tap and content that does not spill off the side.",
           "stays_subjective": "Which content to drop or reorder for small screens."},
 "animate": {"plain": "Motion that is quick enough to feel like feedback, and that gives way when a person asks for less motion.",
             "stays_subjective": "Whether the motion 'feels delightful'."},
 "audit": {"plain": "Run the automated accessibility rules and get a pass or fail list. It tells you what a machine can find, never that the page is good.",
           "stays_subjective": "Everything the rules engines cannot see (meaning, tone, task fit)."},
}

# id, verbs, claim text, delta, basis [(source url, regex, what it supports)], receipts, receipt used as the command, pass criteria, param origin, coverage, disagreement, example, plain
PATTERNS = [
 {"id": "on-grid-spacing", "verbs": ["polish", "layout"], "name": "Spacing sits on a 4px scale",
  "plain": "Every gap and padding is a multiple of 4px, so nothing looks accidentally 7px or 25px.",
  "text": "Padding, margins and gaps are multiples of 4px (a documented spacing scale with a 4-unit base).",
  "delta": ("all elements", "padding / margin / gap", "off-scale values (7px, 25px)", "multiples of 4px"),
  "basis": [(IMP("layout"), r"Use a documented spacing scale rather than one-off values\. A 4-unit base usually provides the useful middle steps that an 8-only scale misses\.", "principle and the 4-unit base")],
  "receipts": ["craft-layout-before", "craft-layout-after", "fix-loop-polish"], "cmd": "craft-layout-after",
  "pass": "no padding, margin or gap on a visible element is off the 4px scale", "param": "source: scale principle and 4-unit base; AXL default: strict multiples of 4px (a project scale can replace it)",
  "coverage": "visible panel only, at the checked width", "disagreement": None,
  "example": "section { margin-top: 24px; }   /* not 25px */"},
 {"id": "readable-contrast", "verbs": ["polish"], "name": "Text contrast is at least 4.5:1", "reuse": "Text has a contrast ratio of at least 4.5:1",
  "plain": "Text is dark enough against its background for most people to read it.", "receipts": ["axe-before-1440", "axe-after-1440", "contrast-before", "contrast-after", "lighthouse-before", "lighthouse-after"]},
 {"id": "visible-focus", "verbs": ["polish"], "name": "Keyboard focus is visible", "reuse": "Keyboard navigation: Missing focus indicators",
  "plain": "When you tab to a button you can see where you are."},
 {"id": "reachable-targets", "verbs": ["polish", "adapt"], "name": "Tap targets are at least 44x44px",
  "plain": "Buttons and inputs are big enough to hit with a thumb.",
  "text": "Interactive targets (buttons, links, inputs) are at least 44x44 CSS pixels.",
  "delta": ("button, a, input, select", "min-width / min-height", "intrinsic size (about 30px tall)", ">= 44px"),
  "basis": [(IMP("adapt"), r"Touch targets 44x44px minimum \(not hover-dependent\)", "44x44px minimum"),
            (WCAG, r"The size of the target for pointer inputs is at least 44 by 44 CSS pixels", "WCAG 2.5.5 (Enhanced, AAA)")],
  "receipts": ["craft-layout-before", "craft-layout-after", "fix-loop-polish"], "cmd": "craft-layout-after",
  "pass": "every visible interactive element measures at least 44x44 CSS px", "param": "source: 44x44 in both sources",
  "coverage": "visible panel only", "disagreement": "WCAG 2.2 AA only requires 24x24 (2.5.8); 44x44 is the AAA / platform-guideline figure",
  "example": "button, input { min-height: 44px; }"},
 {"id": "line-length", "verbs": ["layout", "typeset"], "name": "Running text is at most 80 characters wide",
  "plain": "Paragraphs never stretch so wide that the eye loses its place.",
  "text": "Blocks of running text are no wider than 80 characters per line.",
  "delta": ("p, li", "max-width", "unbounded", "<= 80 characters (about 60ch)"),
  "basis": [(WCAG, r"Width is no more than 80 characters or glyphs \(40 if CJK\)", "WCAG 1.4.8 (AAA)")],
  "receipts": ["craft-measure-before"], "cmd": "craft-measure-before",
  "pass": "no paragraph of more than 80 characters renders wider than about 80 characters", "param": "source: 80 characters",
  "coverage": "estimated from box width and font size", "disagreement": None,
  "example": "p { max-width: 65ch; }"},
 {"id": "reflow", "verbs": ["layout", "adapt"], "name": "Content fits a 320px-wide screen",
  "plain": "On a very small screen nothing forces sideways scrolling.",
  "text": "Vertical-scrolling content reflows at a width equivalent to 320 CSS pixels without horizontal scrolling.",
  "delta": ("page", "horizontal overflow at 320px", "table 332px wide", "no element extends past the viewport"),
  "basis": [(WCAG, r"Vertical scrolling content at a width equivalent to 320 CSS pixels", "WCAG 1.4.10 Reflow")],
  "receipts": ["craft-reflow-375-before", "craft-reflow-320-polished"], "cmd": "craft-reflow-320-polished",
  "pass": "no visible element's right edge is past the 320px viewport", "param": "source: 320 CSS px",
  "coverage": "elements outside data-table scrolling regions are not exempted (WCAG allows two-dimensional content)", "disagreement": None,
  "example": ".data-table { display: block; overflow-x: auto; }"},
 {"id": "running-text-leading", "verbs": ["typeset"], "name": "Running text has line-height of at least 1.5",
  "plain": "Lines of text have enough air between them to read comfortably.",
  "text": "Running text has a line spacing (leading) of at least 1.5 times the font size.",
  "delta": ("p, .subcopy", "line-height", "1.45", ">= 1.5"),
  "basis": [(WCAG, r"Line spacing \(leading\) is at least space-and-a-half within paragraphs", "WCAG 1.4.8 (AAA)")],
  "receipts": ["craft-type-before", "craft-type-after"], "cmd": "craft-type-after",
  "pass": "every paragraph over 40 characters has computed line-height / font-size >= 1.5", "param": "source: 1.5",
  "coverage": "paragraphs and .subcopy only", "disagreement": None,
  "example": "p { line-height: 1.65; }"},
 {"id": "text-size-floor", "verbs": ["typeset", "adapt"], "name": "Text is at least 14px (body 16px)",
  "plain": "Small print is not smaller than 14px; main text is 16px.",
  "text": "Body text is 16px on mobile and secondary text is never below 14px.",
  "delta": ("p, li, td, label, input", "font-size", "13px", ">= 14px (body 16px)"),
  "basis": [(IMP("harden"), r"16px body on mobile, the same floor the typography guidance sets; 14px only for genuinely secondary text", "16px body, 14px floor")],
  "receipts": ["craft-type-before", "craft-type-after"], "cmd": "craft-type-after",
  "pass": "no checked text element computes below 14px", "param": "source: 16px body, 14px secondary; the check enforces the 14px floor only",
  "coverage": "the 16px body rule is not separately checked", "disagreement": None,
  "example": "li, td { font-size: 14px; }"},
 {"id": "motion-duration", "verbs": ["animate"], "name": "State-change motion is 500ms or shorter",
  "plain": "Hover and press feedback is quick; only a deliberate entrance takes longer.",
  "text": "Routine transitions run 500ms or shorter; longer durations are reserved for a deliberately authored focal entrance.",
  "delta": ("*", "transition-duration", "unbounded", "<= 500ms (feedback 100-150ms)"),
  "basis": [(IMP("animate"), r"\| 300–500 ms \| layout, overlay, or view transition \|", "upper band for layout / overlay change"),
            (IMP("animate"), r"\| 500–800 ms \| a deliberately authored focal entrance \|", "longer only for an authored entrance")],
  "receipts": ["craft-duration-unguarded"], "cmd": "craft-duration-unguarded",
  "pass": "no element has a transition-duration above 500ms", "param": "source: duration bands; AXL default: 500ms cap for everything",
  "coverage": "transitions only; animation-duration is not checked", "disagreement": None,
  "example": "button { transition: transform 140ms ease-out; }"},
 {"id": "reduced-motion", "verbs": ["animate", "polish"], "name": "Motion gives way to prefers-reduced-motion",
  "plain": "When a person asks their device for less motion, the interface stops moving things around.",
  "text": "Under prefers-reduced-motion: reduce, no element keeps a transition or animation longer than 1ms.",
  "delta": ("*", "@media (prefers-reduced-motion: reduce)", "transitions run", "transition and animation removed"),
  "basis": [(MDN, r"minimize the amount of non-essential motion", "what the setting means"),
            (IMP("audit"), r"Motion sensitivity\*\*: `prefers-reduced-motion` needs an intentional alternative that preserves state change and hierarchy", "a reduced alternative is required")],
  "receipts": ["reducedmotion-unguarded", "reducedmotion-guarded"], "cmd": "reducedmotion-guarded",
  "pass": "under emulated reduced motion no element has a transition or animation longer than 1ms", "param": "AXL default: 1ms (effectively instant)",
  "coverage": "checks that motion stops; it cannot check that state change is still communicated",
  "disagreement": "The same Impeccable audit page warns against a blanket 0.01ms kill that destroys useful feedback. The check accepts an instant change as compliant and leaves 'is feedback preserved?' to a person.",
  "example": "@media (prefers-reduced-motion: reduce) { * { transition: none; animation: none; } }"},
 {"id": "rules-engine-clean", "verbs": ["audit"], "name": "Automated accessibility rules report no violations",
  "plain": "Run the machine checks (axe-core, Lighthouse) and get a plain pass or fail. Passing does not mean the page is good, only that nothing machine-detectable is broken.",
  "text": "Automated accessibility rule engines (axe-core WCAG 2.0-2.2 A/AA, Lighthouse accessibility audits) report zero violations; they cover only part of WCAG.",
  "delta": ("page", "accessibility rule violations", "2 rules failing (color-contrast, document-title)", "0"),
  "basis": [(AXE, r"find \*\*on average 57% of WCAG issues automatically\*\*", "how much automation covers")],
  "receipts": ["axe-before-1440", "axe-after-1440", "axe-before-375", "axe-after-375", "lighthouse-before", "lighthouse-after"], "cmd": "axe-after-1440",
  "pass": "axe reports 0 violations for tags wcag2a, wcag2aa, wcag21aa, wcag22aa", "param": "source: axe-core's own rule set",
  "coverage": "axe states it finds about 57% of WCAG issues automatically; a clean run is not a full audit", "disagreement": None,
  "example": "npx @axe-core/cli http://localhost:8000 --tags wcag2aa"},
]
