// usage: node craft.js <html> <width> <check[,check...]>
// Computed-style checks on the rendered page. Every check is a pure function of the DOM; findings are deterministic.
// checks: spacing-4  target-44  measure-80  reflow-320  body-16  leading-1.5  duration-500const path = require('path');
const { withPage } = require('./common');
const CHECKS = {
  'spacing-4': `(() => { const out = {}; const props = ['paddingTop','paddingRight','paddingBottom','paddingLeft','marginTop','marginRight','marginBottom','marginLeft','rowGap','columnGap'];
    for (const el of document.querySelectorAll('body, body *')) { if (!el.offsetParent && el.tagName !== 'BODY') continue; const c = getComputedStyle(el);
      for (const p of props) { const v = parseFloat(c[p]); if (!isFinite(v) || v === 0 || c[p] === 'normal') continue; if (c[p].endsWith('%') || c[p] === 'auto') continue; if (Math.round(v * 100) % 400 !== 0) { const k = sel(el) + ' ' + p; out[k] = c[p]; } } }
    return Object.entries(out).map(([k, v]) => ({ location: k.split(' ')[0], property: k.split(' ')[1], value: v, evidence: k.split(' ')[1] + ' ' + v + ' is not a multiple of 4px' })); })()`,
  'target-44': `(() => { const out = []; for (const el of document.querySelectorAll('button, a[href], input:not([type=hidden]), select, textarea, [role=button], [role=switch]')) { if (!el.offsetParent) continue; const r = el.getBoundingClientRect(); if (r.width < 44 || r.height < 44) out.push({ location: sel(el), property: 'min-size', value: Math.round(r.width) + 'x' + Math.round(r.height), evidence: 'target ' + Math.round(r.width) + 'x' + Math.round(r.height) + ' CSS px is below 44x44' }); } return out; })()`,
  'measure-80': `(() => { const out = []; for (const el of document.querySelectorAll('p, li, .subcopy')) { if (!el.offsetParent) continue; const c = getComputedStyle(el); const w = el.getBoundingClientRect().width; const ch = w / (parseFloat(c.fontSize) * 0.5); if (el.textContent.trim().length > 80 && ch > 80) out.push({ location: sel(el), property: 'max-width', value: Math.round(ch) + 'ch~', evidence: 'line box about ' + Math.round(ch) + ' characters wide (limit 80)' }); } return out; })()`,
  'reflow-320': `(() => { const w = document.documentElement.clientWidth; const out = []; for (const el of document.querySelectorAll('body *')) { if (!el.offsetParent) continue; const r = el.getBoundingClientRect(); if (r.right > w + 1 && getComputedStyle(el).position !== 'fixed') out.push({ location: sel(el), property: 'width', value: Math.round(r.right) + 'px', evidence: 'element extends to ' + Math.round(r.right) + 'px in a ' + w + 'px viewport' }); } return out.slice(0, 20); })()`,
  'body-16': `(() => { const out = []; for (const el of document.querySelectorAll('p, li, td, label, input, select, textarea')) { if (!el.offsetParent) continue; const fs = parseFloat(getComputedStyle(el).fontSize); if (fs < 14) out.push({ location: sel(el), property: 'font-size', value: fs + 'px', evidence: 'text is ' + fs + 'px (floor 14px for secondary text)' }); } return out; })()`,
  'leading-1.5': `(() => { const out = []; for (const el of document.querySelectorAll('p, .subcopy')) { if (!el.offsetParent || el.textContent.trim().length < 40) continue; const c = getComputedStyle(el); const lh = c.lineHeight === 'normal' ? 1.2 : parseFloat(c.lineHeight) / parseFloat(c.fontSize); if (lh < 1.5) out.push({ location: sel(el), property: 'line-height', value: lh.toFixed(2), evidence: 'line-height ' + lh.toFixed(2) + ' is below 1.5 for running text' }); } return out; })()`,
  'duration-500': `(() => { const out = []; const ms = v => Math.max(0, ...v.split(',').map(x => x.trim().endsWith('ms') ? parseFloat(x) : (parseFloat(x) * 1000 || 0))); for (const el of document.querySelectorAll('*')) { const c = getComputedStyle(el); const t = ms(c.transitionDuration); if (t > 500) out.push({ location: sel(el), property: 'transition-duration', value: t + 'ms', evidence: 'transition ' + t + 'ms exceeds 500ms' }); } return out; })()`,
};
const HELPER = `window.sel = el => { if (el.id) return '#' + el.id; const cls = (typeof el.className === 'string' ? el.className.trim().split(/\\s+/).filter(Boolean)[0] : ''); return el.tagName.toLowerCase() + (cls ? '.' + cls : ''); };`;
(async () => {
  const [file, width, names] = [process.argv[2], +process.argv[3], (process.argv[4] || '').split(',')];
  const all = await withPage(file, width, async p => { await p.evaluate(HELPER); const r = {}; for (const n of names) { if (!CHECKS[n]) throw new Error('unknown check ' + n); r[n] = await p.evaluate('(function(){const sel=window.sel;return ' + CHECKS[n] + '})()'); } return r; });
  const findings = []; for (const n of names) { const seen = new Set(); for (const f of all[n]) { const k = f.location + f.property + f.value; if (seen.has(k)) continue; seen.add(k); findings.push({ rule_id: n, result: 'fail', evidence: f.evidence, location: f.location, property: f.property, value: f.value }); } }
  findings.sort((a, b) => (a.rule_id + a.location + a.property).localeCompare(b.rule_id + b.location + b.property));
  console.log(JSON.stringify({ tool: 'axl craft checks (Playwright computed style)', width, findings })); process.exit(findings.length ? 1 : 0);
})();
