// usage: node fix.js <html> <width> <out.css> <fixer[,fixer]>   fixers: spacing-4  target-44  contrast
// Closed loop: check -> generate CSS patch ops -> re-check (max 4 rounds). Prints {before, after, rounds}. Patch = `correct` ops as CSS.
const fs = require('fs'), path = require('path');
const { AxeBuilder } = require('@axe-core/playwright');
const { chromium } = require('playwright');
const { CHROME } = require('./common');
const kebab = s => s.replace(/[A-Z]/g, m => '-' + m.toLowerCase());
const snap = px => Math.max(4, Math.round(px / 4) * 4);
const lum = (r, g, b) => { const v = [r, g, b].map(x => x / 255).map(x => x <= 0.03928 ? x / 12.92 : ((x + 0.055) / 1.055) ** 2.4); return 0.2126 * v[0] + 0.7152 * v[1] + 0.0722 * v[2]; };
const ratio = (a, b) => { const [x, y] = [lum(...a), lum(...b)].sort((p, q) => q - p); return (x + 0.05) / (y + 0.05); };
const rgb = h => (h.startsWith('#') ? [1, 3, 5].map(i => parseInt(h.substr(i, 2), 16)) : h.match(/\d+/g).slice(0, 3).map(Number));
function darken(fg, bg, min) { let c = rgb(fg); const b = rgb(bg); for (let i = 0; i < 80 && ratio(c, b) < min; i++) c = c.map(x => Math.max(0, x - 3)); return '#' + c.map(x => x.toString(16).padStart(2, '0')).join(''); }
const HELPER = `window.sel = el => { if (el.id) return '#' + el.id; const cls = (typeof el.className === 'string' ? el.className.trim().split(/\\s+/).filter(Boolean)[0] : ''); return el.tagName.toLowerCase() + (cls ? '.' + cls : ''); };`;
(async () => {
  const [file, width, out, fixers] = [process.argv[2], +process.argv[3], process.argv[4], process.argv[5].split(',')];
  const b = await chromium.launch({ executablePath: CHROME, args: ['--no-sandbox'] });
  const ctx = await b.newContext({ viewport: { width, height: 900 } }); const page = await ctx.newPage();
  await page.goto('file://' + path.resolve(file)); await page.evaluate(HELPER);
  const rules = new Map(); let rounds = 0; const counts = [];
  const craft = fs.readFileSync(path.join(__dirname, 'craft.js'), 'utf8');
  const CH = eval('(' + craft.match(/const CHECKS = (\{[\s\S]*?\n\});\nconst HELPER/)[1] + ')');
  const run = async n => page.evaluate('(function(){const sel=window.sel;return ' + CH[n] + '})()');
  const css = () => [...rules.values()].join('\n');
  const inject = async () => { await page.evaluate(c => { let s = document.getElementById('axl-patch'); if (!s) { s = document.createElement('style'); s.id = 'axl-patch'; document.head.appendChild(s); } s.textContent = c; }, css()); };
  const measure = async () => { let n = 0; if (fixers.includes('spacing-4')) n += (await run('spacing-4')).length; if (fixers.includes('target-44')) n += (await run('target-44')).length;
    if (fixers.includes('contrast')) n += (await new AxeBuilder({ page }).withRules(['color-contrast']).analyze()).violations.flatMap(v => v.nodes).length; return n; };
  const before = await measure();
  for (; rounds < 4; rounds++) {
    if (fixers.includes('spacing-4')) for (const f of await run('spacing-4')) { const px = parseFloat(f.value); rules.set('sp|' + f.location + f.property, `html body ${f.location}{${kebab(f.property)}:${snap(px)}px!important}`); }
    if (fixers.includes('target-44')) for (const f of await run('target-44')) rules.set('tg|' + f.location, `html body ${f.location}{min-height:44px!important;min-width:44px!important}`);
    if (fixers.includes('contrast')) { const r = await new AxeBuilder({ page }).withRules(['color-contrast']).analyze();
      for (const n of r.violations.flatMap(v => v.nodes)) { const d = n.any[0].data; rules.set('ct|' + n.target.join(' '), `${n.target.join(' ')}{color:${darken(d.fgColor, d.bgColor, 4.5)}!important}`); } }
    await inject(); const n = await measure(); counts.push(n); if (n === 0) break;
  }
  const after = await measure(); await b.close();
  fs.writeFileSync(out, '/* generated by axl fix.js: ' + fixers.join(',') + ' */\n' + css() + '\n');
  console.log(JSON.stringify({ tool: 'axl fix.js', fixers, before, after, rounds: counts.length, rules: rules.size, findings: after ? [{ rule_id: 'residual', result: 'fail', evidence: after + ' findings remain', location: file }] : [] }));
  process.exit(after ? 1 : 0);
})();
