#!/usr/bin/env python3
"""axl-correct: apply measurable patches to an HTML file.
  correct.py apply <file.html> <axl.json> --out <out.html>   apply the `correct.ops` of an AXL document (op set/add/remove only)
  correct.py auto  <file.html> --out <out.html> [--width 1440] [--ops-out ops.json]   generate patches for spacing, tap targets and contrast, verify, apply
Patches are appended as one <style id="axl-patch"> block. Anything needing judgment is never patched.
Needs: node + `npm ci` in axl/tools."""
import json, re, subprocess, sys, os, pathlib
AXL = pathlib.Path(__file__).resolve().parents[3]; ROOT = AXL.parent; RUN = AXL / "tools" / "runners"
DEFS = {p["id"]: p["claim_id"] for d in json.load(open(AXL / "data" / "definitions.json"))["definitions"] for p in d["patterns"]}
CLAIM = lambda prop: DEFS["on-grid-spacing"] if re.search(r"padding|margin|gap", prop) else DEFS["reachable-targets"] if "min-" in prop else DEFS["readable-contrast"]
def write(html_in, css, out):
    h = open(html_in, encoding="utf-8").read(); block = f'<style id="axl-patch">\n{css}\n</style>'
    open(out, "w", encoding="utf-8").write(h.replace("</head>", block + "</head>", 1) if "</head>" in h else block + h)
def ops_to_css(ops):
    for o in ops:
        if o["op"] not in ("set", "add", "remove"): raise SystemExit(f"unsupported op {o['op']}")
        if not re.match(r"^clm_[0-9]{4}$", o.get("claim_id", "")): raise SystemExit("every op must cite a claim_id")
    return "\n".join(f"{o['target']}{{{o['property']}:{'unset' if o['op'] == 'remove' else o['value']}!important}}" for o in ops)
def css_to_ops(css):
    return [{"op": "set", "target": m.group(1).strip(), "property": m.group(2).strip(), "value": m.group(3).strip(), "reason": "generated by axl-correct auto (checked, patched, re-checked)", "claim_id": CLAIM(m.group(2))}
            for m in re.finditer(r"([^{}\n/]+)\{([\w-]+):([^;!}]+)(?:!important)?[^}]*\}", css)]
def main():
    a = sys.argv[1:]
    if len(a) < 2 or "--out" not in a: print(__doc__); return 2
    out = a[a.index("--out") + 1]
    if a[0] == "apply":
        d = json.load(open(a[2])); ops = d.get("correct", {}).get("ops", []); write(a[1], ops_to_css(ops), out)
        print(f"applied {len(ops)} ops -> {out}; {len(d.get('correct', {}).get('notes', []))} notes need a person"); return 0
    if a[0] == "auto":
        width = a[a.index("--width") + 1] if "--width" in a else "1440"; tmp = out + ".patch.css"
        r = subprocess.run(["node", str(RUN / "fix.js"), os.path.abspath(a[1]), width, os.path.abspath(tmp), "spacing-4,target-44,contrast"], cwd=ROOT, capture_output=True, text=True, timeout=300)
        res = json.loads(r.stdout.strip().splitlines()[-1]); css = "\n".join(l for l in open(tmp).read().splitlines() if not l.startswith("/*")); os.remove(tmp)
        write(a[1], css, out); ops = css_to_ops(css)
        if "--ops-out" in a: json.dump({"axl": "0.1", "describe": {"surface": "web", "states": ["ready"], "viewports": [f"{width}x900"]}, "correct": {"ops": ops, "notes": []}}, open(a[a.index("--ops-out") + 1], "w"), indent=1)
        print(f"findings before: {res['before']}, after: {res['after']}, patch rules: {res['rules']} -> {out}"); return 0 if res["after"] == 0 else 1
    print(__doc__); return 2
sys.exit(main())
